# Generated by Django 5.2.4 on 2025-07-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="shipping_old_cart",
            field=models.CharField(blank=True, null=True),
        ),
    ]
