# Generated by Django 5.2.4 on 2025-07-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_alter_shippingaddress_shipping_old_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="shipping_old_cart",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
