# Generated by Django 5.2.4 on 2025-07-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_shippingaddress_shipping_old_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderithem",
            old_name="products",
            new_name="product",
        ),
    ]
