# Generated by Django 5.2.4 on 2025-07-18 10:15

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_order_last_update_alter_order_date_ordered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="last_update",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
