# Generated by Django 5.2.4 on 2025-07-18 10:20

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_alter_order_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="last_update",
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
