# Generated by Django 5.2.1 on 2025-07-06 20:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_order_date_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                choices=[("m", 32), ("l", 42), ("xl", 52)], default=42, max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 6, 23, 50, 16, 128208)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.category",
            ),
        ),
    ]
