# Generated by Django 5.2.1 on 2025-07-07 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_sizes_alter_order_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 7, 10, 5, 28, 140447)
            ),
        ),
    ]
