# Generated by Django 5.2.1 on 2025-07-07 10:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_is_sale_product_sale_price_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="star",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 7, 14, 13, 34, 108427)
            ),
        ),
    ]
