# Generated by Django 5.2.1 on 2025-07-07 11:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_order_date_alter_product_star"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 7, 14, 32, 41, 400336)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="star",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
