# Generated by Django 5.2.4 on 2025-07-16 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_order_date_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 16, 9, 47, 15, 264777)
            ),
        ),
    ]
