# Generated by Django 5.2.4 on 2025-07-16 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_profile_old_cart_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 16, 17, 12, 29, 714580)
            ),
        ),
    ]
