# Generated by Django 5.2.4 on 2025-07-18 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 18, 9, 44, 29, 142652)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, null=True),
        ),
    ]
