# Generated by Django 5.2.4 on 2025-07-18 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_order_date_alter_profile_old_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 18, 9, 45, 18, 520479)
            ),
        ),
    ]
