# Generated by Django 5.2.4 on 2025-07-18 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 18, 12, 55, 50, 356799)
            ),
        ),
    ]
